import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import {
  AccessPermissionDocument,
  AccessPermissionSchema,
  AuditLogDocument,
  AuditLogSchema,
  BatchDocument,
  BatchScheduleDocument,
  BatchScheduleSchema,
  BatchSchema,
  ChatMessageDocument,
  ChatAttachmentFileDocument,
  ChatAttachmentFileSchema,
  ChatMessageSchema,
  ChatReadStateDocument,
  ChatReadStateSchema,
  ClassSessionDocument,
  ClassSessionAttendanceSnapshotDocument,
  ClassSessionAttendanceSnapshotSchema,
  ClassSessionMaterialDocument,
  ClassSessionMaterialSchema,
  ClassSessionSchema,
  ConsumerDocument,
  ConsumerSchema,
  EmailVerificationTokenDocument,
  EmailVerificationTokenSchema,
  ModerationDocument,
  ModerationSchema,
  ParticipantDocument,
  ParticipantSchema,
  PasswordResetTokenDocument,
  PasswordResetTokenSchema,
  PlatformEventDocument,
  PlatformEventSchema,
  PermissionDocument,
  PermissionSchema,
  ProducerDocument,
  ProducerSchema,
  RedisStreamEndpointDocument,
  RedisStreamEndpointSchema,
  RecordingDocument,
  RecordingSchema,
  RoleDocument,
  RolePermissionDocument,
  RolePermissionSchema,
  RoleSchema,
  RoomDocument,
  RoomIncidentEventDocument,
  RoomIncidentEventSchema,
  RoomSnapshotBundleDocument,
  RoomSnapshotBundleSchema,
  RoomSchema,
  SessionDocument,
  SessionSchema,
  StudentEnrollmentDocument,
  StudentEnrollmentSchema,
  UserRoleDocument,
  UserRoleSchema,
  UserDocument,
  UserSchema,
  WebhookDeliveryDocument,
  WebhookDeliverySchema,
  WebhookEndpointDocument,
  WebhookEndpointSchema
} from './schemas';

@Module({
  imports: [
    MongooseModule.forFeature([
      { name: UserDocument.name, schema: UserSchema },
      { name: BatchDocument.name, schema: BatchSchema },
      { name: StudentEnrollmentDocument.name, schema: StudentEnrollmentSchema },
      { name: BatchScheduleDocument.name, schema: BatchScheduleSchema },
      { name: ClassSessionDocument.name, schema: ClassSessionSchema },
      { name: ClassSessionAttendanceSnapshotDocument.name, schema: ClassSessionAttendanceSnapshotSchema },
      { name: ClassSessionMaterialDocument.name, schema: ClassSessionMaterialSchema },
      { name: RoleDocument.name, schema: RoleSchema },
      { name: AccessPermissionDocument.name, schema: AccessPermissionSchema },
      { name: RolePermissionDocument.name, schema: RolePermissionSchema },
      { name: UserRoleDocument.name, schema: UserRoleSchema },
      { name: SessionDocument.name, schema: SessionSchema },
      { name: PasswordResetTokenDocument.name, schema: PasswordResetTokenSchema },
      { name: EmailVerificationTokenDocument.name, schema: EmailVerificationTokenSchema },
      { name: AuditLogDocument.name, schema: AuditLogSchema },
      { name: RoomDocument.name, schema: RoomSchema },
      { name: RoomIncidentEventDocument.name, schema: RoomIncidentEventSchema },
      { name: RoomSnapshotBundleDocument.name, schema: RoomSnapshotBundleSchema },
      { name: PlatformEventDocument.name, schema: PlatformEventSchema },
      { name: WebhookEndpointDocument.name, schema: WebhookEndpointSchema },
      { name: RedisStreamEndpointDocument.name, schema: RedisStreamEndpointSchema },
      { name: WebhookDeliveryDocument.name, schema: WebhookDeliverySchema },
      { name: ParticipantDocument.name, schema: ParticipantSchema },
      { name: ProducerDocument.name, schema: ProducerSchema },
      { name: ConsumerDocument.name, schema: ConsumerSchema },
      { name: PermissionDocument.name, schema: PermissionSchema },
      { name: ModerationDocument.name, schema: ModerationSchema },
      { name: ChatAttachmentFileDocument.name, schema: ChatAttachmentFileSchema },
      { name: ChatMessageDocument.name, schema: ChatMessageSchema },
      { name: ChatReadStateDocument.name, schema: ChatReadStateSchema },
      { name: RecordingDocument.name, schema: RecordingSchema }
    ])
  ],
  exports: [MongooseModule]
})
export class DatabaseModule {}
